version: '3'

services:
    php:
      build: .
      volumes:
            - .:/app
      restart: always
      container_name: accessyoutube
      networks:
        - youtube

networks:
  youtube:
    external: true